"""create taskcategory, hardroutine and task tables

Revision ID: 555551c59223
Revises: 77a1711f08c3
Create Date: 2026-04-04 19:45:35.726929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '555551c59223'
down_revision: Union[str, Sequence[str], None] = '77a1711f08c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hard_routines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weekdays', postgresql.ARRAY(sa.Enum('sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', name='weekday_enum')), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('task_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('scheduling_flexibility', sa.Enum('L', 'M', 'H', name='flexibility_enum'), nullable=True),
    sa.Column('energy_required', sa.Enum('L', 'M', 'H', name='energy_enum'), nullable=True),
    sa.Column('needs_focus_block', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('flexibility', sa.Enum('L', 'M', 'H', name='flexibility_enum'), nullable=False),
    sa.Column('energy_required', sa.Enum('L', 'M', 'H', name='energy_enum'), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(), nullable=False),
    sa.Column('estimated_duration', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('actual_start', sa.DateTime(), nullable=True),
    sa.Column('actual_end', sa.DateTime(), nullable=True),
    sa.Column('actual_duration', sa.Integer(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'in_progress', 'completed', 'skipped', 'cancelled', name='status_enum'), nullable=False),
    sa.CheckConstraint('priority >= 1 AND priority <= 5', name='priority_range'),
    sa.ForeignKeyConstraint(['category_id'], ['task_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('task_categories')
    op.drop_table('hard_routines')
    # ### end Alembic commands ###
