"""added UserProfile, DailySchedule and Task Segment tables, along with an enum for status of tasks

Revision ID: 6bab31afdb78
Revises: 7b1298230de0
Create Date: 2026-04-12 08:19:53.923773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bab31afdb78'
down_revision: Union[str, Sequence[str], None] = '7b1298230de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_schedules',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('work_start', sa.Time(timezone=True), nullable=False),
    sa.Column('sleep_start', sa.Time(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('default_work_start', sa.Time(timezone=True), nullable=False),
    sa.Column('default_sleep_start', sa.Time(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_segments')
    op.drop_table('user_profiles')
    op.drop_table('daily_schedules')
    # ### end Alembic commands ###
