"""enable timezones in datetime fields and remove an unnecessary field in task model

Revision ID: 76dad150d702
Revises: a92fb5819622
Create Date: 2026-04-10 21:57:10.178402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76dad150d702'
down_revision: Union[str, Sequence[str], None] = 'a92fb5819622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('hard_routines')
    op.drop_table('task_categories')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('scheduling_flexibility', postgresql.ENUM('L', 'M', 'H', name='flexibility_enum'), autoincrement=False, nullable=True),
    sa.Column('energy_required', postgresql.ENUM('L', 'M', 'H', name='energy_enum'), autoincrement=False, nullable=True),
    sa.Column('needs_focus_block', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('task_categories_pkey')),
    sa.UniqueConstraint('name', name=op.f('task_categories_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('hard_routines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('weekdays', postgresql.ARRAY(postgresql.ENUM('sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', name='weekday_enum')), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('hard_routines_pkey')),
    sa.UniqueConstraint('name', name=op.f('hard_routines_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('flexibility', postgresql.ENUM('L', 'M', 'H', name='flexibility_enum'), autoincrement=False, nullable=False),
    sa.Column('energy_required', postgresql.ENUM('L', 'M', 'H', name='energy_enum'), autoincrement=False, nullable=False),
    sa.Column('scheduled_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('estimated_duration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scheduled_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('actual_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('actual_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('actual_duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('actual_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('scheduled', 'in_progress', 'completed', 'skipped', 'cancelled', name='status_enum'), autoincrement=False, nullable=False),
    sa.CheckConstraint('priority >= 1 AND priority <= 5', name=op.f('priority_range')),
    sa.ForeignKeyConstraint(['category_id'], ['task_categories.id'], name=op.f('tasks_category_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tasks_pkey'))
    )
    # ### end Alembic commands ###
