"""remove TaskSegments model

Revision ID: e2361b3e6d1d
Revises: 6bab31afdb78
Create Date: 2026-04-12 11:24:39.088700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2361b3e6d1d'
down_revision: Union[str, Sequence[str], None] = '6bab31afdb78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE status_enum ADD VALUE IF NOT EXISTS 'paused'")
    op.drop_table('task_segments')
    op.add_column('tasks', sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('last_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('parent_task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'parent_task_id')
    op.drop_column('tasks', 'last_started_at')
    op.drop_column('tasks', 'actual_end')
    op.create_table('task_segments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('task_segments_task_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('task_segments_pkey'))
    )
    # ### end Alembic commands ###
